const menu = [
  {
    id: 1,
    name: 'layout',
    path: '/',
    parent_id: 0,
    icon: 'el-icon-monitor',
    title: '工作台',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: '',
    component: 'Layout',
    redirect: '/index',
    sort: 999999,
    role_menus: {
      id: 82,
      role_id: 17,
      menu_id: 1,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 27,
    name: 'ProjectManagement',
    path: '/projectManagement',
    parent_id: 0,
    icon: 'el-icon-s-data',
    title: '项目',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'Layout',
    redirect: '/projectManagement/ProjectLists',
    sort: 888888,
    role_menus: {
      id: 88,
      role_id: 17,
      menu_id: 27,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 25,
    name: 'departmentManagement',
    path: '/departmentManagement',
    parent_id: 0,
    icon: 'el-icon-s-check',
    title: '部门',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'Layout',
    redirect: '/departmentManagement/departmentManagement',
    sort: 777777,
    role_menus: {
      id: 86,
      role_id: 17,
      menu_id: 25,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 28,
    name: 'ProjectList_1',
    path: 'ProjectList/1',
    parent_id: 32,
    icon: 'el-icon-tickets',
    title: '全部项目',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/projectList/index',
    redirect: '',
    sort: 400,
    role_menus: {
      id: 90,
      role_id: 17,
      menu_id: 28,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 32,
    name: 'ProjectLists',
    path: 'ProjectLists',
    parent_id: 27,
    icon: 'iconfont icon-caidan1',
    title: '项目列表',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'EmptyLayout',
    redirect: '/projectManagement/ProjectLists/ProjectList/1',
    sort: 300,
    role_menus: {
      id: 89,
      role_id: 17,
      menu_id: 32,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 29,
    name: 'ProjectList_2',
    path: 'ProjectList/2',
    parent_id: 32,
    icon: 'el-icon-star-off',
    title: '我的收藏',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/projectList/index',
    redirect: '',
    sort: 300,
    role_menus: {
      id: 91,
      role_id: 17,
      menu_id: 29,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 39,
    name: 'mention',
    path: 'mention',
    parent_id: 38,
    icon: 'iconfont icon-xiaoxi',
    title: '@我',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/messageManagement/index',
    redirect: null,
    sort: 300,
    role_menus: {
      id: 97,
      role_id: 17,
      menu_id: 39,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 30,
    name: 'ProjectList_3',
    path: 'ProjectList/3',
    parent_id: 32,
    icon: 'el-icon-s-cooperation',
    title: '已归档项目',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/projectList/index',
    redirect: null,
    sort: 200,
    role_menus: {
      id: 92,
      role_id: 17,
      menu_id: 30,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 33,
    name: 'ProjectTemplate',
    path: 'ProjectTemplate',
    parent_id: 27,
    icon: 'el-icon-notebook-1',
    title: '项目模板',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/projectTemplate/index',
    redirect: null,
    sort: 200,
    role_menus: {
      id: 94,
      role_id: 17,
      menu_id: 33,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 40,
    name: 'inform',
    path: 'inform',
    parent_id: 38,
    icon: 'iconfont icon-tongzhi',
    title: '通知',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/messageManagement/index',
    redirect: null,
    sort: 200,
    role_menus: {
      id: 98,
      role_id: 17,
      menu_id: 40,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 31,
    name: 'ProjectList_4',
    path: 'ProjectList/4',
    parent_id: 32,
    icon: 'el-icon-delete',
    title: '回收站',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/projectList/index',
    redirect: null,
    sort: 100,
    role_menus: {
      id: 93,
      role_id: 17,
      menu_id: 31,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 38,
    name: 'Message',
    path: 'message',
    parent_id: 27,
    icon: 'iconfont icon-lingdang-xianxing',
    title: '消息提醒',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'EmptyLayout',
    redirect: null,
    sort: 100,
    role_menus: {
      id: 96,
      role_id: 17,
      menu_id: 38,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 41,
    name: 'personal',
    path: 'personal',
    parent_id: 38,
    icon: 'iconfont icon-icon--',
    title: '私信',
    hidden: 0,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/messageManagement/index',
    redirect: null,
    sort: 100,
    role_menus: {
      id: 99,
      role_id: 17,
      menu_id: 41,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 34,
    name: 'Project',
    path: 'Project/:id',
    parent_id: 27,
    icon: null,
    title: '项目',
    hidden: 1,
    always_show: 1,
    keep_alive: 0,
    target: null,
    component: 'views/projectManagement/project/index',
    redirect: null,
    sort: 1,
    role_menus: {
      id: 95,
      role_id: 17,
      menu_id: 34,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 15,
    name: 'Index',
    path: 'index',
    parent_id: 1,
    icon: 'home',
    title: '首页',
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/index/index',
    redirect: null,
    sort: 0,
    role_menus: {
      id: 83,
      role_id: 17,
      menu_id: 15,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 22,
    name: 'personalCenter',
    path: '/personalCenter',
    parent_id: 0,
    icon: null,
    title: null,
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'Layout',
    redirect: 'personalCenter',
    sort: 0,
    role_menus: {
      id: 84,
      role_id: 17,
      menu_id: 22,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 23,
    name: 'PersonalCenter',
    path: 'personalCenter',
    parent_id: 22,
    icon: null,
    title: '个人中心',
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/personalCenter/index',
    redirect: null,
    sort: 0,
    role_menus: {
      id: 85,
      role_id: 17,
      menu_id: 23,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 26,
    name: 'DepartmentManagement',
    path: 'departmentManagement',
    parent_id: 25,
    icon: '',
    title: '部门管理',
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/departmentManagement/index',
    redirect: null,
    sort: 0,
    role_menus: {
      id: 87,
      role_id: 17,
      menu_id: 26,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 35,
    name: 'invite',
    path: '/invite',
    parent_id: 0,
    icon: 'el-icon-bell',
    title: '邀请',
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'EmptyLayout',
    redirect: null,
    sort: 0,
    role_menus: {
      id: 100,
      role_id: 17,
      menu_id: 35,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
  {
    id: 36,
    name: 'project',
    path: 'project/:id',
    parent_id: 35,
    icon: null,
    title: '项目邀请',
    hidden: 1,
    always_show: 0,
    keep_alive: 0,
    target: null,
    component: 'views/invite/ProjectInvite',
    redirect: null,
    sort: 0,
    role_menus: {
      id: 101,
      role_id: 17,
      menu_id: 36,
      created_at: '2021-09-09 00:20:10',
      updated_at: '2021-09-09 00:20:10',
    },
  },
];
export default menu;
