// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBacktop: typeof import('element-plus/es')['ElBacktop'];
    ElBadge: typeof import('element-plus/es')['ElBadge'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElCollapse: typeof import('element-plus/es')['ElCollapse'];
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElEmpty: typeof import('element-plus/es')['ElEmpty'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElMessage: typeof import('element-plus/es')['ElMessage'];
    ElMessageBox: typeof import('element-plus/es')['ElMessageBox'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElProgress: typeof import('element-plus/es')['ElProgress'];
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElResult: typeof import('element-plus/es')['ElResult'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSpace: typeof import('element-plus/es')['ElSpace'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    EnProcess: typeof import('./components/EnProcess.md')['default'];
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default'];
    IAkarIconsPeopleGroup: typeof import('~icons/akar-icons/people-group')['default'];
    IAntDesignUsergroupAddOutlined: typeof import('~icons/ant-design/usergroup-add-outlined')['default'];
    IBiBell: typeof import('~icons/bi/bell')['default'];
    ILaLanguage: typeof import('~icons/la/language')['default'];
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default'];
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default'];
    ImgSet: typeof import('./components/imgSet.vue')['default'];
    IMingcuteDepartmentLine: typeof import('~icons/mingcute/department-line')['default'];
    IOcticonPeople16: typeof import('~icons/octicon/people16')['default'];
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default'];
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default'];
    IRiArticleLine: typeof import('~icons/ri/article-line')['default'];
    IRiUserForbidLine: typeof import('~icons/ri/user-forbid-line')['default'];
    IUiwUser: typeof import('~icons/uiw/user')['default'];
    LazyLoading: typeof import('./components/LazyLoading.vue')['default'];
    PopUp: typeof import('./components/popUp.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TheFooter: typeof import('./components/TheFooter.vue')['default'];
    ZhProcess: typeof import('./components/ZhProcess.md')['default'];
  }
}
